### ISSUE TITLE
long类型数据显示不全

### ISSUE THREAD

**Issue by hannes-wan** [WhiteCosmos/Gotcha-HTTP-Client-Support#13]
Java Long类型在这个应用中显示不全，例如311893230188761088会显示成311893230188761100，用curl测试了一下，应该是应用的问题
解决方法也很简单，在获取这种类型的数字时转化成字符串就好，望快速解决

**Comment by WhiteCosmos** [comment]
> Java Long类型在这个应用中显示不全，例如311893230188761088会显示成311893230188761100，用curl测试了一下，应该是应用的问题 解决方法也很简单，在获取这种类型的数字时转化成字符串就好，望快速解决

是在哪个功能里面显示不全？

**Comment by hannes-wan** [comment]
![](https://user-images.githubusercontent.com/36161712/228672990-fcda979f-320f-4b86-9929-6746df0ac03f.png)

在Response部分

有些Java API的 id 喜欢直接用Java Long类型来返回，而不是将Long类型转化为String类型再返回，我猜测这个应用是用Javascript写的，而Javascript中因为没有long类型，会对比number类型更长的数字直接精度丢失，如果是Javascript，我以前用json-bigint这个库解决过这个问题

如果是使用curl或者是paw，它们都能显示出正确的数字

**Comment by WhiteCosmos** [comment]
> 

最新的1.6.4版本已修复该问题，Number类型统一使用BigNumber包装。
