### ISSUE TITLE
粘贴的request地址不能正确解析

### ISSUE THREAD

**Issue by sharkfly666** [WhiteCosmos/Gotcha-HTTP-Client-Support#3]
![image](https://user-images.githubusercontent.com/6223662/146674418-c02b5f83-e6e0-4aad-9de5-e3cacc35eca9.png)

如果新建request  粘贴url到地址栏 然后解析出来的只有127.0.0.1

**Comment by WhiteCosmos** [comment]
感谢反馈，将在下一个版本中修复。

**Comment by WhiteCosmos** [comment]
已在 1.3.15 版本中修复
