### ISSUE TITLE
Are there issues with compressed data in response?

### ISSUE THREAD

**Issue by i-johnso** [WhiteCosmos/Gotcha-HTTP-Client-Support#5]
I'm having issues with body responses not being displayed. The response is being sent back compressed via gzip. Is this supported?

Testing in other tools, such as postman or curl, I can see the response body with the same request.

**Comment by WhiteCosmos** [comment]
The gzip response format is supported. Could you tell me what the actual content-type is ?

**Comment by i-johnso** [comment]
The response body is JSON data, the content-type header in the repose is 

content-type: application/frdy+json; charset=utf-8

**Comment by WhiteCosmos** [comment]
Ok, I will fix it in next version.

**Comment by WhiteCosmos** [comment]
Fixed in 1.4.1 version
