### ISSUE TITLE
添加pre-request功能

### ISSUE THREAD

**Issue by 2771428814** [WhiteCosmos/Gotcha-HTTP-Client-Support#6]
用postman的pre-request功能在请求发起前处理一部分数据，比如说生成签名。将数据放到环境变量中，再通过赋值获取计算的数据。这个功能最好能添加上，不然很多接口都没有办法迁移到这个工具上。

**Comment by WhiteCosmos** [comment]
这类功能会通过和Paw的Dynamic Values类似的方式实现，不会像Postman一样直接在应用内写脚本

**Comment by WhiteCosmos** [comment]
1.4.9 版本已添加动态变量功能，目前支持枚举，日期时间，环境变量和全局变量，欢迎体验~
